Uploading original results notebook
aimpowered/NLPdisparity pull request #1
Opened 2023-05-04 17:21 UTC by gpric024

This is the file you can use to re-create our base results. Just note I have not entirely run it as I already have the results and it takes quite some time to run.

2023-05-10 21:58 UTC, Shaomei requested changes
Hi Greg,

I took a quick pass and left some comments that you may want to address before sending out more API calls. 

Overall the code looks clean and easy to read, good job! Eventually we would need to pull them out of notebook and restructure them into classes and scripts, for better readability and reproducibility, maybe after we are more or less code complete.

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +      "Homophones for over: []\n",
Can we trim the entries in the homophone dict with empty values? It could make lookup more efficient.

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +    "#this list was created by me and copied from the following website: https://www.grammarly.com/blog/confusing-letters/"
Perhaps better to use the grammarly list plus some other letter confusion set as described in the literature? E.g. 
file:///Users/shaomeiwu/Downloads/Rello_Baeza_Llisterri_DysList_14%20(1).pdf

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +    "                    homophone = random.choice(homophones_dict[word])\n",
Given that the homophone dict contains the key word itself (e.g.  " 'site': ['site', 'cite', 'sight']), will we pick the same word at this step?

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +    "                    words_changed += 1\n",
It looks like this counter will be inflated if multiple letters within a word are changed.

The words_changed counter can also be inflated if a word is first swapped with its homophone than have letter swapped. E.g. flu -> flew -> flem, we will increment words_changes twice but only we only changed one word here "flu". 

I think we should delete line 2967 and 2983, and only update this counter in the end of the "for i" loop: we will first keep the original value of current word and check whether it is changed before we move on to the next word.

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +      "Words changed: 53\n"
As I commented above, this counter is greatly inflated.

2023-05-10 21:58 UTC, Shaomei commented on injecting_errors.ipynb
> +    "                    letters_swapped += 1\n",
Given that having more than one letter misspelled is significantly less common (see file:///Users/shaomeiwu/Downloads/Rello_Baeza_Llisterri_DysList_14%20(1).pdf), we might want to either exit the (for j) loop after one successful swapping, or temporarily decrease p2 to reduce the probability of second letter swapping.

2023-05-11 16:08 UTC, gpric024 commented on injecting_errors.ipynb
> +      "Homophones for over: []\n",
Done!

2023-05-11 16:16 UTC, gpric024 commented on injecting_errors.ipynb
> +    "#this list was created by me and copied from the following website: https://www.grammarly.com/blog/confusing-letters/"
I reviewed our list, and I took into account the paper, unfortunately, the majority of mistakes are Spanish-specific (% wise). With that in mind, I updated the list bit so that we use similar logic for dyslist (i.e. vowels and consonants that are similar in sound or digital look).

2023-05-11 16:17 UTC, gpric024 commented on injecting_errors.ipynb
> +    "                    homophone = random.choice(homophones_dict[word])\n",
You are right! This has been addressed

2023-05-11 16:32 UTC, gpric024 commented on injecting_errors.ipynb
> +    "                    words_changed += 1\n",
Fixed!

2023-05-11 16:34 UTC, gpric024 commented on injecting_errors.ipynb
> +    "                    letters_swapped += 1\n",
How much should we decrease p2 to? Like half of the probability, a quarter or even less? I can also make it so we decide the factor it decreases by

2023-05-26 17:16 UTC, closed without merging